### ISSUE TITLE
DBへの接続

### ISSUE THREAD

**Issue by rokoucha** [atnanasi/sibwive#1]
DBに接続してMarkdownの記事を読み出す。
形はこんな感じ？
`{
    "name": "unique name",
    "title": "sample article",
    "date": "2016-10-10T00:40:00.000",
    "description": "hogehogepiyopiyo",
    "article": "hogehogehogehoghoeghoehgoeoghegoheogoe"
`

**Comment by rinsuki** [comment]
必要な属性を決めたほうがいい
e.g.
- title
- text
- created_at
- updated_at
- etc...

**Comment by rokoucha** [comment]
@Petitsurume

具体的にどうすればいいのかさっぱり分からなかった
DBの属性部と記事データ部で分ければいいって事？

**Comment by rokoucha** [comment]
理解した
- title
- created_at
- updated_at
- author
- text

問題はtextには原文（パーサ前）を入れないと編集時に爆死する
コンパイル済みとコンパイル前で分けて保存する？

**Comment by rinsuki** [comment]
- text
- text_html

**Comment by rokoucha** [comment]
ありがたう

**Comment by rokoucha** [comment]
`{ "title": "hogehoge", "created_at": "2016-10-10T00:40:00.000", "update_at": "2016-10-10T00:40:00.000", "author": "hogepiyo", "text": "#hogepiyo hogehoge", "text_html": "<h1>hogepiyp</h1> hogehoge"}`

**Comment by rokoucha** [comment]
`{ "name": "hogename", "title": "hogehoge", "created_at": "2016-10-10T00:40:00.000", "update_at": "2016-10-10T00:40:00.000", "author": "hogepiyo", "text": "#hogepiyo hogehoge", "text_html": "<h1>hogepiyp</h1> hogehoge"}`
URL用にname
