### ISSUE TITLE
エラー

### ISSUE THREAD

**Issue by tosuke** [atnanasi/sibwive#13]
index.dt(6,81): Error: found ';' when expecting ','
index.dt(7,79): Error: found ';' when expecting ','
index.dt(8,1): Error: found 'EOF' when expecting ')'
index.dt(8,1): Error: found 'EOF' when expecting ';' following statement
../../.dub/packages/vibe-d-0.7.29/vibe-d/source/vibe/templ/diet.d(47,51): Error: template instance sibwive.index.index.compileDietFileIndent!("index.dt", 0, config_system, config_user) error instantiating
../../.dub/packages/vibe-d-0.7.29/vibe-d/source/vibe/http/server.d(210,42):        instantiated from here: compileDietFile!("index.dt", config_system, config_user)
source/sibwive/index.d(6,5):        instantiated from here: render!("index.dt", config_system, config_user)

**Comment by rokoucha** [comment]
731942fd32402d0814d679149258f4b676f27782 余分な「(」があったので修正
